### PR TITLE
Fix documentation for store.findCookies, missing allowSpecialUseDomain property

### PR DESCRIPTION
**Pull request by bryzaguy**

### CODE REVIEW

**Comment by bryzaguy** [comment]
Signing the CLA failed on first attempt. Trying to sign again tells me I've already signed it.

**Review by colincasey — APPROVED** [review]

**Comment by colincasey** [comment]
@awaterma can you review and approve also?

**Review by awaterma — APPROVED** [review]
Approved.

**Comment by awaterma** [comment]
@colincasey -- let's merge this on Monday when we all meet.

**Comment by awaterma** [comment]
Thanks Will!

**Pull request merged**
