### PR TITLE
Downgrade ip-regex dependency to support node 6

### LINKED ISSUE #140: Unable to install v3.0.0 on node 6.14.0
Since today I'm unable to install tough-cookie on node v6.14.0, because I'm getting the following error: 

`error ip-regex@3.0.0: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.14.0"`

I suspect that the introduction of `ip-regex` in PR #138 (and especially [this commit](https://github.com/salesforce/tough-cookie/commit/eff9118f3c960bc1ed378ebb5ec2e80930cd3138)) causes that, because `ip-regex ^3.0.0` needs at least node v8.

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #140

### CODE REVIEW

**Comment by ccoenen** [comment]
This dependency is blocking a release of CodiMD at the moment. We previously announced dropping support of node 6 close to the official end of life of node 6. We already deprecated it, but I would hate to break a promise we made. I would therefore like to request to merge this pull request.

**Comment by Turbo87** [comment]
@stash friendly reminder in case you didn't see this PR yet. would be great to get this released as a v3.0.1 as apparently a lot of projects are currently failing CI due to this 😢 

if you need help, please let us know. I'm happy to help resolve this.

**Comment by aleclarson** [comment]
@stash The radio silence is not appreciated. This is a very simple fix, and CI builds are breaking without it. Please help! 😢

**Comment by awaterma** [comment]
Sorry about this guys; we're meeting today and will discuss. I'll pickup the review.

**Comment by stash** [comment]
@aleclarson hey, I'm sorry about the radio silence. I would be just as unappreciative in your shoes. My email notifications were not working and I don't log into github every day. Please accept my apologies. I got @awaterma to witness me turning email notifications back on over our video chat today, so it shouldn't happen again. Some further context: https://github.com/salesforce/tough-cookie/issues/140#issuecomment-460500637

@simonihmig thank you for this PR

**Pull request merged**
