### PR TITLE
132 str trim not a function

### PR DESCRIPTION
**Pull request by awaterma**
I think this should provide a fix for issue #11, as well as I can tell. Please take a look.

@medelibero-sfdc @ruoho @ruoho-sfdc @ShivanKaul 

Thanks!

### CODE REVIEW

**Comment by awaterma** [comment]
@medelibero-sfdc -- I've updated the test and corrected parse validation based on that work. :) I think this is now ready to merge. We should wait on Travis; but everything passes locally.

**Review by medelibero-sfdc — APPROVED** [review]
LGTM

**Comment by awaterma** [comment]
Merged this today after our meeting with @medelibero-sfdc and @ruoho-sfdc.

**Comment by awaterma** [comment]
Referenced the incorrect issue above, this closes out #132.

**Pull request merged**
