### PR TITLE
fix(cookie-jar): use typeof for checking type of option

### PR DESCRIPTION
**Pull request by SimenB**
Works around https://github.com/facebook/jest/issues/2549 when used in Jest

### CODE REVIEW

**Comment by ianbytchek** [comment]
Ping! Can this be merged now?

**Comment by alvis** [comment]
is there anything blocking this from merging?

**Comment by ShivanKaul** [comment]
LGTM to me too. Shipping 🚢

**Comment by theKashey** [comment]
Any ETA to actually release at least as a beta?

**Comment by awaterma** [comment]
We'll get a release discussion going in our next meeting. We have a few more p/rs we want to bring in, I think.

I think you can do some local testing with our master branch by pulling in a GitHub dependency into your package.json.

**Comment by theKashey** [comment]
Went with [patch-package](https://github.com/ds300/patch-package) solution for now.

**Pull request merged**
