### PR TITLE
Added unit test for issue 144; passing in master.

### PR DESCRIPTION
**Pull request by awaterma**
Additional unit test for #144.

### CODE REVIEW

**Comment by awaterma** [comment]
@ShivanKaul -- would you mind taking a look? I think this is a simple p/r.

**Comment by awaterma** [comment]
I'll sign these and update.

**Comment by medelibero-sfdc** [comment]
@awaterma Your test uses `getCookiesSync` while the problem referenced in issue 144 uses `getCookies`. If you use `getCookies` you will get the error but if you use `getCookiesSync` it works.

**Comment by awaterma** [comment]
Thanks @medelibero-sfdc! I've modified the test and reproduced locally. I'll see if I can fix the underlying issue. I'll close this out and resubmit later.

**Pull request closed without merging**
