### PR TITLE
Added istanbul to generate code coverage for the project.

### PR DESCRIPTION
**Pull request by awaterma**
Simple changes to package.json to add Istanbul support and a coverage runscript target.

### CODE REVIEW

**Comment by stash-sfdc** [comment]
Actually, please add both `.gitignore` and `.npmignore` entries since I see that the docker stuff is going to add the latter. :)

**Comment by awaterma** [comment]
I've pulled in the changes for the .gitignore file, but this branch is pretty far behind. I'm thinking I may want to sync with the latest, and then create a new pull request with the Istanbul changes. LMK.

**Comment by awaterma** [comment]
I've synced and rebased the salesforce org master branch against my own "istanbul" branch and pushed that work back up. This has no conflicts and should have the .gitignore file updated as requested. I've retained the existing .npmignore file. Kindly take a look!

**Comment by awaterma** [comment]
I've pushed up an update that has my GPG signature.

**Comment by awaterma** [comment]
Closing this and opening a new pull request with the latest Istanbul release -- "nyc."

**Pull request closed without merging**
