### PR TITLE
Added NYC coverge and reporting to tough-cookie.

### PR DESCRIPTION
**Pull request by awaterma**
Pulled in NYC (Istanbul 2.0) into our package.json. Did a few runs with the local package, set it up to do html based coverage reporting (through vows).

### CODE REVIEW

**Comment by stash** [comment]
The overall coverage also looks pretty good. 

image

**Comment by stash** [comment]
Looking through `cookie.js` there are both some trivial and important-to-test branches that aren't getting tested for. I'd like to shoot for 90+% if we can. However, we should at the very least not regress in coverage now ;)

**Comment by awaterma** [comment]
Definitely agreed on keeping coverage up and working to extend the numbers
where possible. :)

There's a configuration we can add to NYC that will enforce a coverage
number, which might be a good idea to pull in and start incrementing as we
get progress:

https://www.npmjs.com/package/nyc#checking-coverage

I'll make those other changes this week and update the P/R!

**Comment by stash** [comment]
Still just need the `.gitignore` and `.npmignore` changes

**Comment by awaterma** [comment]
Updated as discussed. :)

**Pull request merged**
