### PR TITLE
Revert " use eslint and prettier to apply consistent, modern formatting"

### PR DESCRIPTION
**Pull request by awaterma**
Reverts salesforce/tough-cookie#155

3 tests are failing after the merge.

### CODE REVIEW

**Comment by awaterma** [comment]
Reverting. I will also reopen the pull request (if possible) and @jstewmon and I can work together on the failing tests (if he's open to that).

**Comment by jstewmon** [comment]
I'm taking a look. I saw the failures locally earlier when I was checking the wall clock time of lint / test, but thought it must have been a local issue since the tests were previously passing. 😕

**Comment by jstewmon** [comment]
The `ietf_data/parser.json` file has expiration dates that elapsed recently.

**Comment by awaterma** [comment]
Thank you @jstewmon. I just ran the tests against the previous top-level and see the same failures; I'll take a look at the ietf_data/parser.json and update.

**Comment by jstewmon** [comment]
Tests are fixed on my `modernize` branch

**Comment by awaterma** [comment]
Can you prepare another p/r? I can compare locally; running out of time today, but should be able to get the fix in tomorrow.

**Comment by jstewmon** [comment]
You got it: #168

**Pull request merged**
